LOAD DATA INFILE 'DIR/customer.tbl' INTO TABLE customer FIELDS TERMINATED BY '|';
LOAD DATA INFILE 'DIR/lineitem.tbl' INTO TABLE lineitem FIELDS TERMINATED BY '|';
LOAD DATA INFILE 'DIR/nation.tbl' INTO TABLE nation FIELDS TERMINATED BY '|';
LOAD DATA INFILE 'DIR/orders.tbl' INTO TABLE orders FIELDS TERMINATED BY '|';
LOAD DATA INFILE 'DIR/part.tbl' INTO TABLE part FIELDS TERMINATED BY '|';
LOAD DATA INFILE 'DIR/partsupp.tbl' INTO TABLE partsupp FIELDS TERMINATED BY '|';
LOAD DATA INFILE 'DIR/region.tbl' INTO TABLE region FIELDS TERMINATED BY '|';
LOAD DATA INFILE 'DIR/supplier.tbl' INTO TABLE supplier FIELDS TERMINATED BY '|';